# Workflow to deploy the HPI Schul-Cloud application next upcomming Release branch to the staging instance
# The later invocation query parameters at start to identify the image tag to be deployed.
# Parameters:
#   branch-prefix : feature|develop|release|hotfix|master
#   team-no       : the team number to identify the machine hotfix<team-no>.schul-cloud.dev
#   ticket-id     : either the JIRA ticket-id used in the branch or the version numer for release and master branches

name: sc-app-deploy-release-staging

# Controls when the action will run.
on:
  repository_dispatch:
    # SC-apps send repository dispatch event
    inputs:
      GIT_BRANCH:
        description: "The full branch name to use."
        required: true
        default: ""
      TRIGGER_REPOSITORY:
        description: "Trigger sending app. Always required."
        required: true
        default: ""
      VERSION:
        description: "version of app"
        required: true
        default: ""
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      # Setting environment variables here make them available for all steps
      CI_GITHUB_TRAVISUSER_SWARMVM_KEY: ${{ secrets.CI_GITHUB_TRAVISUSER_SWARMVM_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      IS_RELEASE_VERSION: 'false'
    defaults:
      # Setting defaults for all steps, this require the first action must check-out the code
      run:
        working-directory: ./sc-app-deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it must be on first place to allow central setting of working directory
      - uses: actions/checkout@v2
      - name: Echo parameter
        run: |
          echo "GITHUB event trigger: ${{ github.event_name }}"
          echo "GITHUB input GIT_BRANCH:  ${{ github.event.client_payload.GIT_BRANCH }}"
          echo "GITHUB input TRIGGER_REPOSITORY:  ${{ github.event.client_payload.TRIGGER_REPOSITORY }}"
          echo "GITHUB input app VERSION: ${{ github.event.client_payload.VERSION }}"
         
      - name: Display working directory
        # Just for failure analysis to track down possible issues occurring for invalid host configurations
        run: |
          ls -la .
          env
          chmod a+x ./sc-app-deploy.py
        shell: bash
      - name: unmask version an compare to NEXT_RELEASE version
        run: |
          APP_VERSION=$( echo ${{ github.event.client_payload.VERSION }} | tr -s "-" "."  )
          echo APP_VERSION:"$APP_VERSION"
          if [[ $APP_VERSION == ${{ secrets.NEXT_RELEASE }} ]]
          then
            IS_RELEASE_VERSION="true"
            echo "IS_RELEASE_VERSION is true"
            echo IS_RELEASE_VERSION="true" >> $GITHUB_ENV
          else
            echo "workflow will abort: release version is NOT version of NEXT_RELEASE. No deployment to staging."
          fi

      - name: cancel workflow if Version of NEXT_RELEASE NOT meets VERSION
        if: ${{ env.IS_RELEASE_VERSION == 'false' }}
        uses: andymckay/cancel-action@0.2
      
      # Run the deployment to hotfix6 for testing with feature-branch
      # set Branch Prefix

      - name: Running feature deployment for hotfix
       # if: github.event.client_payload.VERSION == secrets.NEXT_RELEASE
        run: ./sc-app-deploy.py --deployhost team --branchprefix feature --teamnumber 6 --jiraid OPS-1559

      # Add deploy next release to staging
      # add staging host to ./sc-app-deploy.py
 
